-- Insert 24 virtue seeds (hạt giống đức tính)
INSERT INTO public.seeds (name, color, sort_order) VALUES
  ('Biết đủ',     'amber',   1),
  ('Biết lỗi',   'violet',  2),
  ('Biết ơn',    'teal',    3),
  ('Can đảm',    'emerald', 4),
  ('Cần thận',   'rose',    5),
  ('Cầu tiến',   'purple',  6),
  ('Chăm chỉ',   'orange',  7),
  ('Chân thành', 'lime',    8),
  ('Chính kiến', 'purple',  9),
  ('Chính trực', 'green',   10),
  ('Chủ động',   'indigo',  11),
  ('Đam mê',     'blue',    12),
  ('Điềm đạm',   'lime',    13),
  ('Độc lập',    'cyan',    14),
  ('Động lực',   'red',     15),
  ('Giúp đỡ',   'amber',   16),
  ('Hiếu thảo',  'indigo',  17),
  ('Học hỏi',    'sky',     18),
  ('Hợp tác',    'pink',    19),
  ('Hưng phấn',  'orange',  20),
  ('Khát vọng',  'amber',   21),
  ('Khen tặng',  'green',   22),
  ('Khiêm tốn',  'rose',    23),
  ('Khoan dung', 'teal',    24);
